# Markdown Linting Workflow
# This workflow checks for Markdown formatting consistency and link validity.

name: Markdown Linting

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
        
      - name: Run Markdown Lint
        run: markdownlint '**/*.md' --ignore node_modules
        
      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/markdown-link-check-config.json'
          folder-path: '.'
          max-depth: -1 